[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
build_flags = -DAUDIO_BLOCK_SAMPLES=128

lib_deps =
    https://github.com/arozcan/MFRC522-I2C-Library.git
    bblanchon/ArduinoJson @ ^7.0.0